### ISSUE TITLE
can i use you pdf bot in termux ?

### ISSUE THREAD

**Issue by johnredfield2099** [SharonAliyas5573/PDF_BOT#1]
i trying to figure out to use you pdfbot in termux ,
i want to download all book from this search (japanese)

**Comment by SharonAliyas5573** [comment]
not for mobile users

**Comment by johnredfield2099** [comment]
> 

can you tell me how to install and use you pdfbot in windows 7?
 step by step,  
 thanks you.

**Comment by SharonAliyas5573** [comment]
I have provided the information for running on windows in the readme, refer to it and if you still have problems I'll be glad to assist you.
